server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: springstudentsz
          uri: http://localhost:8080
          predicates:
            - Path=/students/**
          filters:
            # Если вызываем URL вида /students/api/v1/students, то удаляем префикс "/students"
            - RewritePath=/students/(?<remaining>.*), /${remaining}
        - id: book_service
          uri: lb://book_service
          predicates:
            - Path=/books/**
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
