PUT http://localhost:8081/api/v1/students/update_student
Content-Type: application/json

#{
#  "firstName": "Edit1",
#  "lastName": "fdsfds",
#  "dateOfBirth": "1981-01-01",
#  "email": "lDYVAzqn@jyOuwjW.us",
#  "groupName": "Математика"
#}

###

POST http://localhost:8081/api/v1/books
Content-Type: application/json

{
  "title": "Spring Boot",
  "author": "John Doe",
  "isbn": "123456"
}

###

