//GET http://localhost:8080/api/v1/students

POST http://localhost:8080/api/v1/students/save_student/1
Content-Type: application/json

{
  "firstName": "{{$random.name.firstName}}",
  "lastName": "{{$random.name.lastName}}",
  "dateOfBirth": "1990-01-01",
  "email": "{{$random.email}}"

}

