
#Поиск по почте
#GET http://localhost:8080/api/v1/students/bDR7HR54Fdac@lneY.io

#фильтрация
#GET http://localhost:8080//api/v1/students?firstName=Benton

#сортировка
#GET http://localhost:8080/api/v1/students?sort=lastName,asc

#пагинация
#GET http://localhost:8080/api/v1/students?sort=lastName,asc&page=0&size=5

#фильтр по группе (выводит всю группу)
#GET  http://localhost:8080/api/v1/students?group.name=Математика

#сортировка по группе
#GET http://localhost:8080/api/v1/students?sort=group.name,asc

#сортировка по имени из группы "математика"
#GET http://localhost:8080/api/v1/students?group.name=Математика&sort=firstName,asc


GET http://localhost:8081/api/v1/students/book/3523?email=gm5Kk@IyAXs.cy

###

GET http://localhost:8081/api/v1/books/

###

